package org.our.scala.lessons

import org.apache.spark.sql.types._

object SchemasToUse {
  val schema_races = new StructType()
    .add(StructField("raceId", IntegerType, nullable = false))
    .add(StructField("year", IntegerType, nullable = false))
    .add(StructField("round", IntegerType, nullable = false))
    .add(StructField("circuitId", IntegerType, nullable = false))
    .add(StructField("name", StringType, nullable = false))
    .add(StructField("date", DateType, nullable = false))
    .add(StructField("time", TimestampType, nullable = false))
    .add(StructField("url", StringType, nullable = false))

  val schema_drivers = new StructType()
    .add(StructField("driverId", IntegerType, nullable = false))
    .add(StructField("driverRef", StringType, nullable = false))
    .add(StructField("number", IntegerType, nullable = true))
    .add(StructField("code", StringType, nullable = true))
    .add(StructField("forename", StringType, nullable = false))
    .add(StructField("surname", StringType, nullable = false))
    .add(StructField("dob", DateType, nullable = false))
    .add(StructField("nationality", StringType, nullable = false))
    .add(StructField("url", StringType, nullable = false))

  val schema_results = new StructType()
    .add(StructField("resultId", IntegerType, nullable = false))
    .add(StructField("raceId", IntegerType, nullable = false))
    .add(StructField("driverId", IntegerType, nullable = false))
    .add(StructField("constructorId", IntegerType, nullable = false))
    .add(StructField("number", IntegerType, nullable = true))
    .add(StructField("grid", IntegerType, nullable = true))
    .add(StructField("position", IntegerType, nullable = true))
    .add(StructField("positionText", StringType, nullable = true))
    .add(StructField("positionOrder", IntegerType, nullable = true))
    .add(StructField("points", DoubleType, nullable = true))
    .add(StructField("laps", IntegerType, nullable = true))
    .add(StructField("time", StringType, nullable = true))
    .add(StructField("milliseconds", IntegerType, nullable = true))
    .add(StructField("fastestLap", IntegerType, nullable = true))
    .add(StructField("rank", IntegerType, nullable = true))
    .add(StructField("fastestLapTime", StringType, nullable = true))
    .add(StructField("fastestLapSpeed", DoubleType, nullable = true))
    .add(StructField("statusId", IntegerType, nullable = true))
}
